UPDATE ms1_site SET domain = 'wp.test.com', path = '/' WHERE id = '1';
UPDATE ms1_blogs SET domain = 'wp.test.com';
UPDATE ms1_options SET option_name = 'home', option_value = 'http://wp.test.com', autoload = 'yes' WHERE option_id = '36';
UPDATE ms1_options SET option_value='http://wp.test.com' WHERE option_id='1';
UPDATE `ms1_2_options` SET `option_value` = 'http://wp.test.com/successstories' WHERE `option_id` = '36';
UPDATE `ms1_2_options` SET `option_value` = 'http://wp.test.com/successstories' WHERE `option_id` = '1';
UPDATE `ms1_3_options` SET `option_value` = 'http://wp.test.com/darkside' WHERE `option_id` = '36';
UPDATE `ms1_3_options` SET `option_value` = 'http://wp.test.com/darkside' WHERE `option_id` = '1';
UPDATE `ms1_4_options` SET `option_value` = 'http://wp.test.com/blogs' WHERE `option_id` = '36';
UPDATE `ms1_4_options` SET `option_value` = 'http://wp.test.com/blogs' WHERE `option_id` = '1';
UPDATE `ms1_5_options` SET `option_value` = 'http://wp.test.com/tonyhortonfitness' WHERE `option_id` = '36';
UPDATE `ms1_5_options` SET `option_value` = 'http://wp.test.com/tonyhortonfitness' WHERE `option_id` = '1';
UPDATE `ms1_6_options` SET `option_value` = 'http://wp.test.com/wtr' WHERE `option_id` = '36';
UPDATE `ms1_6_options` SET `option_value` = 'http://wp.test.com/wtr' WHERE `option_id` = '1';
UPDATE `ms1_7_options` SET `option_value` = 'http://wp.test.com/coachsuccessstories' WHERE `option_id` = '36';
UPDATE `ms1_7_options` SET `option_value` = 'http://wp.test.com/coachsuccessstories' WHERE `option_id` = '1';
UPDATE `ms1_8_options` SET `option_value` = 'http://wp.test.com/beachbody-classic/' WHERE `option_id` = '36';
UPDATE `ms1_8_options` SET `option_value` = 'http://wp.test.com/beachbody-classic/' WHERE `option_id` = '1';
UPDATE `ms1_9_options` SET `option_value` = 'http://wp.test.com/beachbodyblog' WHERE `option_id` = '36';
UPDATE `ms1_9_options` SET `option_value` = 'http://wp.test.com/beachbodyblog' WHERE `option_id` = '1';
